# Concatenation of Tuples (+)
'''t1=(45,'Rohith',29)
t2=('Ngm','wgl',2.84)
td=t1+t2
print(td)

#Repetition of Tuples (*)
t1=(45,'Ravula',30)
print(t1*4)

#indexing
t1=(2,4,6,8,3,5,7,2,4,5,3,7,9,3)
print(f"Length of t1 is: {len(t1)}")
print(f"Index of 3 in t1 is: {(t1.index(3))}")
print(f"If 7 is present in t1: {(7 in t1)}")
#min, max, sum
t2=(6,3,5,14,18,10,2,9)
print(f"Smallest no. in t2 is: {(min(t2))}")
print(f"Largest no. in t2 is: {(max(t2))}")
print(f"sum of all the no.s in t2 is: {(sum(t2))}")'''

t1=('Rohith','Uma','Rudhvika')
#t1.append('Ravula')
print(t1, type(t1))
t1=list(t1)
print(t1, type(t1))
t1.append('Rudhransh')
print(f"Adding Rudhransh Beta to family: {t1}")
t1.extend(['Rajasambaiah','Vanamala'])
print(f'Adding Mom and Dad to family: {t1}')
t1.insert(0,'Ravula')
print(f'Adding Surname to family: {t1}')
print(t1)
print(type(t1))
t1=tuple(t1)
print(t1, type(t1))
t1=list(t1)
t1.extend(['Laxmi','Ganesh'])
print(f"Black sheeps entered in t1:\n{t1}")
t1.insert(2,'Srikanth')
print(f"Freekanth wants to talk to her sister:\n{t1}")
t1.remove('Ganesh')
print(t1)
t1.pop(2)
print(t1)
t1.pop(-1)
print(t1)
print(f'My family is\n{t1}')
